### ISSUE TITLE
upgrading is tricky...

### ISSUE THREAD

**Issue by petaflot** [GenPi64/gentoo-on-rpi-64bit#21]
emerge @world fails to execute gracefully without quite some fiddling around.

I found the enormous list of dependencies (notably when "core" is set), such as three text editors (who needs this really?) and more problematic is the fact that

- sys-firmware/brcm43430-firmware
- sys-kernel/bcmrpi3-kernel-bin

don't exist.

also, I'm pretty sure I downloaded the minimal image, but xfce4 is set!

**Comment by samip5** [comment]
They don't exist because technically upgrading from Sakaki's out-of-date image is no-longer supported by us and we use our own ebuild for kernel.
