### ISSUE TITLE
Invitation To Participate in Discord Fails

### ISSUE THREAD

**Issue by jlpoolen** [GenPi64/gentoo-on-rpi-64bit#23]
This project states on 1/22/2022:

      Open an issue here, or join the Discord server at https://discord.gg/a9VqTGHPy6

I click through to Discord and I accept the invite:

![firefox_2022-01-22_17-43-30](https://user-images.githubusercontent.com/227313/150661414-09345f88-cf54-4fea-a94b-af03fb7840c1.png)

When I am in the forum, I select the lobby hash.  I'm told I cannot send messages on the channel (#lobby).  There ought to be instructions on what to do in order to participate, or something needs to be changed on the Discord side.
![firefox_2022-01-22_17-44-20](https://user-images.githubusercontent.com/227313/150661420-f1df8e97-99d9-4746-b1b7-d9a715c27da6.png)

Otherwise, as it is now, there's no point to clicking through to Discord.

**Comment by jonesmz** [comment]
Sorry about the trouble.

Here's a new link : https://discord.gg/BHbMbUBHjZ

**Comment by jlpoolen** [comment]
I tried the link: https://discord.gg/BHbMbUBHjZ

Had the same experience, when I arrived, and even after selecting "#lobby", I have the same dark letters stating I may not post.

**Comment by jonesmz** [comment]
Oh. My mistake.

You have to click the green checkbox. Doing that will let you access the other chat rooms

Its a spam prevention tool

**Comment by perkinslr** [comment]
@jlpoolen If you need further assistance feel free to send me a DM on discord; I @mentioned you in the channel you need to use.

**Comment by jlpoolen** [comment]
I direct messaged perkinslr.  For propriety, here is the screen I see and the only green box, Like/Disklike, that I checked.
![firefox_2022-01-23_06-09-06](https://user-images.githubusercontent.com/227313/150682685-96693b1d-c4cc-4bc4-98c5-4077b197f5f3.png)

**Comment by jlpoolen** [comment]
I played around with clicking the check box for Carl-bot and noticed the column to the left changing and I that was in #bugs, so I tried ?#general" and it looks like I'm in the discussion/channel/discord/group.
Thank you.
