### ISSUE TITLE
alpha9 build.sh dependent on working servers

### ISSUE THREAD

**Issue by jlpoolen** [GenPi64/gentoo-on-rpi-64bit#25]
In the alpha9 branch, I tried running the build.sh and it failed; see #24.  This was during a time, January 22-23, 2022, when the link on this projects page for genpi64-lite-latest.img.zst at  https://packages.genpi64.com/genpi-aarch64-lite-latest.img.zst failed, but the mirror link at https://fi.packages.genpi64.com/genpi-aarch64-lite-latest.img.zst worked.  

I haven't dug into the script tree, but it appears the build.sh script depends upon successfully downloading from packages.genpi64.com.

It might be helpful to be able to configure the URL into a variable so a mirror could be selected during times the main server has problems, or use an environmental variable, i.e. GENPI64_SERVER defaulting to "packages.genpi64.com" but could be changed to "fi.packages.genpi64.com".

**Comment by samip5** [comment]
These two things are not related.
