### ISSUE TITLE
Server for Download of Binary Images is Offline

### ISSUE THREAD

**Issue by jlpoolen** [GenPi64/gentoo-on-rpi-64bit#29]
March 9, 2020 8:00 a.m. PST

The link at the GenPi64 GitHub page for the full install: genpi64-arm64-openrc-desktop-alpha9.img.zst results in: 

Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
Apache/2.4 Server at s3.genpi64.com Port 443

I'm in the Discord group GenPi64 and posted a notification there in the "General" discussion group that the server is down.

**Comment by jlpoolen** [comment]
Looks like the servers are up, so it must be something about Apache.

    jlpoole@ares /usr/local/src $ date;ping -c 2 genpi64.com
    Wed Mar  9 08:12:25 PST 2022
    PING genpi64.com (45.55.3.11) 56(84) bytes of data.
    64 bytes from 45.55.3.11 (45.55.3.11): icmp_seq=1 ttl=56 time=18.3 ms
    64 bytes from 45.55.3.11 (45.55.3.11): icmp_seq=2 ttl=56 time=18.0 ms

    --- genpi64.com ping statistics ---
    2 packets transmitted, 2 received, 0% packet loss, time 1001ms
    rtt min/avg/max/mdev = 17.977/18.160/18.344/0.183 ms
    jlpoole@ares /usr/local/src $ date;ping -c 2 s3.genpi64.com
    Wed Mar  9 08:12:34 PST 2022
    PING web-ha.kapsi.fi (91.232.155.81) 56(84) bytes of data.
    64 bytes from web-ha.kapsi.fi (91.232.155.81): icmp_seq=1 ttl=56 time=184 ms
    64 bytes from web-ha.kapsi.fi (91.232.155.81): icmp_seq=2 ttl=56 time=184 ms

    --- web-ha.kapsi.fi ping statistics ---
    2 packets transmitted, 2 received, 0% packet loss, time 1002ms
    rtt min/avg/max/mdev = 183.706/183.870/184.034/0.164 ms
    jlpoole@ares /usr/local/src $

I tried sftp and scp, but could not connect.  I'm guessing those serves are not activated.  I was hoping there might be an alternative way to download the images when Apache is not responding.

**Suggestion**: have at port 80 an index.html page giving the name of the project and how to reach the maintainers, e.g. Discord and/or logging an Issue at GiHub, and/or provide an alternative way to obtain the images?

**Comment by samip5** [comment]
This has been fixed, issue was related to an hoster's backend appserver reboot.
