### ISSUE TITLE
sync issue [fix]

### ISSUE THREAD

**Issue by mcdubhghlas** [GenPi64/gentoo-on-rpi-64bit#34]
I was having an error when trying to update. The error was basically that the branch didn't exist.

It was corrected when I changed the `sync-git-clone-extra-opts` line in /etc/portage/repos.conf/genpi64.conf

`#sync-git-clone-extra-opts = --single-branch --branch alpha9` to `sync-git-clone-extra-opts = --single-branch --branch master`.

**Comment by jonesmz** [comment]
You installed an older image that was for development testing.

Newer nearly-nightly-build images are available https://s3.genpi64.com/images/

E.g. https://s3.genpi64.com/images/nullGenPi64Systemd.img.zst

Join our discord for more prompt updates: https://discord.gg/BHbMbUBHjZ

**Comment by samip5** [comment]
> You installed an older image that was for development testing.
> 
> Newer nearly-nightly-build images are available https://s3.genpi64.com/images/
> 
> E.g. https://s3.genpi64.com/images/nullGenPi64Systemd.img.zst
> 
> Join our discord for more prompt updates: https://discord.gg/BHbMbUBHjZ

The issue is that the README has links to alpha9 version. :)

**Comment by mcdubhghlas** [comment]
Oh. I had corrected the error myself and just updated everything myself. This is good to know, we should update the README file as per @samip5

Edit: Unfortunately, I do not have a discord account and do not plan to. Is there an alternative way to get this information?

**Comment by jonesmz** [comment]
the github has all the dev activity. Just hard to miss announcement style things if we dont update the readme file.
