### ISSUE TITLE
Over The Rainbow

### ISSUE THREAD

**Issue by woofwoof** [GenPi64/gentoo-on-rpi-64bit#39]
Apologies for reaching out but any ideas please where I should start to get around a persistent 'rainbow screen' on boot on a Raspberry Pi Zero 2 W? The only alternative I tried which also failed was a PINN install. I did amend the recommended file there to account for devices (a TFT screen & fan) attached to the GPIO - could those peripherals be the root of the persistent rainbow on a native install (using Balena Etcher under Windows)? Thanks again for any help...

**Comment by jonesmz** [comment]
I tested this to work on recent build (e.g. any build newer than summer 2022)

Please join us on discord to get more rapid help

https://discord.gg/QWU59Tyy26

**Comment by woofwoof** [comment]
I'm sorry I kind of got distracted. I got this working on a Raspberry Pi 4 absolutely no problem but it never worked on my Raspberry Pi Zero 2. I am closing the comment as that did the trick really. Thank you.

**Comment by jonesmz** [comment]
Hrmm. I did get it working on the pi0w2. What image were you trying? Maybe a newer one would work?

We're still having trouble with out build server producing images reliably.

Have time to help us out?
